version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    env_file: ./.env
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  url-cut:
    container_name: url_cut_app
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file: ./.env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8080:8080"
    depends_on:
      - postgres
